### ISSUE TITLE
建议尽早把马娘和支援卡的配置独立出来

### ISSUE THREAD

**Issue by xulai1001** [hzyhhzy/UmaAi#1]
方便扩展功能

另外想请教一下使用的评价算法的详情

**Comment by hzyhhzy** [comment]
支援卡这个事情我之后整理一下，暂时先凑合用，主要是想冲UD。
评价算法是：
1，写一个模拟器，尽可能还原游戏本身
2，手写一个比较简单的养马逻辑
3，蒙特卡洛法：在实际游戏中，对于每一个选项，点下去之后用手写逻辑模拟育成10000局，取平均分最大的那个选项

**Comment by xulai1001** [comment]
马娘扩展我直接来弄了_(:з」∠)_
