### ISSUE TITLE
找不到UmaAi.exe

### ISSUE THREAD

**Issue by yue9432** [hzyhhzy/UmaAi#26]
您好我照着上面的步骤执行都没有问题，但没有找到UmaAi.exe可以打开。
是不是少了什么步骤没做?
谢谢您

**Comment by tomliu1923** [comment]
![image](https://github.com/hzyhhzy/UmaAi/assets/84729282/c8ec6307-91e6-4b75-aa15-cf7bf08e3aa7)
你好，我試著透過visual studio編譯但出現相當多錯誤，請問我是否缺少了什麼套件?

**Comment by hzyhhzy** [comment]
现在只有qq群里有完整的整合包，可以加群，或者过两天我在github发release

**Comment by hzyhhzy** [comment]
已发release
