### ISSUE TITLE
編譯錯誤

### ISSUE THREAD

**Issue by tomliu1923** [hzyhhzy/UmaAi#27]
![image](https://github.com/hzyhhzy/UmaAi/assets/84729282/cf80a097-1a67-4af5-91a9-d669dffbaae9)
你好，我試著透過visual studio 2022進行編譯，但出現了不少錯誤，請問我是不是缺少了什麼套件未安裝?

**Comment by hzyhhzy** [comment]
可能是简体中文编码问题，具体怎么解决我不清楚，我这里没问题

**Comment by tomliu1923** [comment]
謝謝，確實是編碼問題，我將檔案改為ansi格式就可以了
但我開始執行並開始育成後仍然持續顯示找不到packets/current gs的檔案，這時候的report analyzer 已經有正確讀到資料了，我去current gs的路徑找也沒有看到這個檔案

**Comment by hzyhhzy** [comment]
还需要魔改的”小黑板“，可以下载最新release然后阅读使用说明
