### ISSUE TITLE
数据源

### ISSUE THREAD

**Issue by Weidows** [hzyhhzy/UmaAi#28]
这个项目的数据更新比较快和全面:
https://github.com/wrrwrr111/pretty-derby/blob/master/src/assert/db.json
也有没满破的卡面数据

**Comment by hzyhhzy** [comment]
感谢提醒。但是现在其实已经使用了同样的数据。相关代码在Scripts/export_support_card里。这些数据的主要问题是没有写清楚“固有“词条
