### ISSUE TITLE
问一下我开着这个程式打Apex会被封吗

### ISSUE THREAD

**Issue by LAMLITony** [hzyhhzy/UmaAi#29]
我想问一下这个程式在运行中或是未运行的状态下会否被其他游戏的防作弊所检测使其他游戏的帐号被封?如Apex,无畏契约等

**Comment by xulai1001** [comment]
这个程序和小黑板都是针对马娘开发的，而且并没有作弊功能。
别的反作弊不要管得太宽就不可能有问题

**Comment by LAMLITony** [comment]
> 這個程序和小黑板都是針對馬娘開發的，而且並沒有作弊功能。 其他反作弊不要管得太寬就不可能有問題

那我用个U盘把这程式装起来,用的时候用U盘开会比较安全对吗?

**Comment by hzyhhzy** [comment]
你猜
