### ISSUE TITLE
release錯誤嗎?

### ISSUE THREAD

**Issue by dyinlake** [hzyhhzy/UmaAi#53]
![text](https://github.com/hzyhhzy/UmaSimulator/assets/167905471/0bb1e740-6812-4a4a-a3c9-297328fb1701)
因爲不能加入QQ 所以直接下載源代碼進行編譯 但是在這個階段無法跳過 請問這是release的問題嗎？
只有基本的C++知識請告訴我這個錯誤謝謝

**Comment by hzyhhzy** [comment]
Sorry I would not provide more information
