### ISSUE TITLE
是編譯錯誤嗎?

### ISSUE THREAD

**Issue by dyinlake** [hzyhhzy/UmaAi#54]
![text](https://github.com/hzyhhzy/UmaSimulator/assets/167905471/24e1ab13-2a73-444d-bea2-c3fc72f8404c)
因爲不能加入QQ所以直接下載源代碼進行編譯但是在這個階段無法跳過請問這是release錯誤嗎？
只有基本的C++知識請告訴我這個錯誤謝謝

**Comment by hzyhhzy** [comment]
Sorry I would not provide more information. Try to solve it by yourself
