### ISSUE TITLE
错误和如何下载 / Errors & How to Download

### ISSUE THREAD

**Issue by umskskak** [hzyhhzy/UmaAi#55]
我是来自日本的用户。
我能够设置 UmamusumeResponseAnalyzer，但当我启动 umaAI.exe 时，它提示 "Unicode 字符映射不在目标多字节代码页上。 (原创）Unicode 文字のマッピングがターゲットのマルチバイト　コード　ページにありません。“，后面是 ”ユメイサオスpackets/thisTurn.json」ヤソノトワハヌモ・ウノホソェハシサ。コレー衾エユ・ウ」ケ、ラ"信息。
我们想知道如何修复这个错误，以及使用最新版本所需的链接。
或许还可以提供一些视频教程，以避免像我这样的无知者今后再提出问题。
我用的是翻译，我觉得写得不好。 致以最诚挚的问候。
![Desktop Screenshot 2024 04 28 - 07 52 52 49](https://github.com/hzyhhzy/UmaSimulator/assets/68580147/3dc7d631-1142-4656-a20b-aab1b892079b)

**Comment by hzyhhzy** [comment]
Many people think this is an "illegal tool". So I would not provide more information for the installation. Later I will publish a "completely legal" version, whose status is inputed manually so it will not need any modification to the game itself.
